repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude_types: [svg]
      - id: check-yaml
      - id: mixed-line-ending
        args: [--fix=lf]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.3.1"
    hooks:
      - id: prettier
        exclude_types: [markdown, yaml]
